#!/bin/sh
uci -q batch << EOF
delete network.baklan

set network.baklan=interface
set network.baklan.proto='static'
set network.baklan.device='br-lan'
set network.baklan.ipaddr='192.168.31.1'
set network.baklan.netmask='255.255.255.0'
set network.baklan.ip6assign='60'
set network.baklan.force_link='1'

commit network
EOF

echo "✅ Backup LAN (baklan 192.168.31.1) added successfully on first boot!"
